[build]
  base = "website/"
  publish = "build/"
  command = "npm run build"

[build.environment]
  REACT_APP_BASE_URL = "/"
  CI = "false"
  NODE_VERSION = "16.14.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
